export const OSRS_SKILLS = [
  'Attack',
  'Strength',
  'Defense',
  'Hitpoints',
  'Ranged',
  'Prayer',
  'Magic',
  'Cooking',
  'Woodcutting',
  'Fletching',
  'Fishing',
  'Firemaking',
  'Crafting',
  'Smithing',
  'Mining',
  'Herblore',
  'Agility',
  'Thieving',
  'Slayer',
  'Farming',
  'Runecrafting',
  'Construction',
] as const;

export type OSRSSkill = typeof OSRS_SKILLS[number];

export const SKILL_DESCRIPTIONS: Record<string, string> = {
  Attack: 'Offensive combat and striking power',
  Strength: 'Raw physical power and resistance training',
  Defense: 'Protection and resilience',
  Hitpoints: 'Overall health and endurance',
  Ranged: 'Precision and distance training',
  Prayer: 'Meditation and mindfulness',
  Magic: 'Learning and mental acuity',
  Cooking: 'Nutrition and meal preparation',
  Woodcutting: 'Outdoor activities and forestry',
  Fletching: 'Dexterity and fine motor skills',
  Fishing: 'Patience and relaxation',
  Firemaking: 'Passion and igniting change',
  Crafting: 'Creative expression and making',
  Smithing: 'Discipline and hard work',
  Mining: 'Digging deep and persistence',
  Herblore: 'Health knowledge and herbalism',
  Agility: 'Flexibility and cardio training',
  Thieving: 'Stealth and strategy',
  Slayer: 'Defeating challenges and goals',
  Farming: 'Growth and cultivation',
  Runecrafting: 'Energy and transformation',
  Construction: 'Building and creating structure',
};

export const SKILL_COLORS: Record<string, string> = {
  Attack:       '#cc3333',
  Strength:     '#ff8833',
  Defense:      '#4488cc',
  Hitpoints:    '#cc3333',
  Ranged:       '#44aa44',
  Prayer:       '#dde8aa',
  Magic:        '#6688ff',
  Cooking:      '#e09030',
  Woodcutting:  '#558833',
  Fletching:    '#44aa66',
  Fishing:      '#4499cc',
  Firemaking:   '#ff6622',
  Crafting:     '#cc8844',
  Smithing:     '#aaaaaa',
  Mining:       '#8877cc',
  Herblore:     '#44cc55',
  Agility:      '#ffcc33',
  Thieving:     '#aa44bb',
  Slayer:       '#dd2222',
  Farming:      '#77aa33',
  Runecrafting: '#ddaaff',
  Construction: '#cc9955',
};

// Static requires are mandatory for React Native's Metro bundler
export const SKILL_ICONS: Record<string, ReturnType<typeof require>> = {
  Attack:       require('../../assets/icons/skills/attack.png'),
  Strength:     require('../../assets/icons/skills/strength.png'),
  Defense:      require('../../assets/icons/skills/defence.png'),
  Hitpoints:    require('../../assets/icons/skills/hitpoints.png'),
  Ranged:       require('../../assets/icons/skills/ranged.png'),
  Prayer:       require('../../assets/icons/skills/prayer.png'),
  Magic:        require('../../assets/icons/skills/magic.png'),
  Cooking:      require('../../assets/icons/skills/cooking.png'),
  Woodcutting:  require('../../assets/icons/skills/woodcutting.png'),
  Fletching:    require('../../assets/icons/skills/fletching.png'),
  Fishing:      require('../../assets/icons/skills/fishing.png'),
  Firemaking:   require('../../assets/icons/skills/firemaking.png'),
  Crafting:     require('../../assets/icons/skills/crafting.png'),
  Smithing:     require('../../assets/icons/skills/smithing.png'),
  Mining:       require('../../assets/icons/skills/mining.png'),
  Herblore:     require('../../assets/icons/skills/herblore.png'),
  Agility:      require('../../assets/icons/skills/agility.png'),
  Thieving:     require('../../assets/icons/skills/thieving.png'),
  Slayer:       require('../../assets/icons/skills/slayer.png'),
  Farming:      require('../../assets/icons/skills/farming.png'),
  Runecrafting: require('../../assets/icons/skills/runecrafting.png'),
  Construction: require('../../assets/icons/skills/construction.png'),
};
